===============these are just important examples==================                    
============these are not interactive=============                       
=============so pay attention=========================

In [ ]:
candy_purchased = 0                                         # counter variable

while candy_purchased <= 5:
  print('Candy purchased: ' + str(candy_purchased))
  candy_purchased += 1                                      # print increment by 1


Candy purchased: 0
Candy purchased: 1
Candy purchased: 2
Candy purchased: 3
Candy purchased: 4
Candy purchased: 5


In [ ]:
def purchases_100(sales):
    count = 0                           # Set a counter of totals > 100
    for customer in sales:              # Loop over each inner list
        customer_total = 0              # Set 0 value of purchases for the inner list
        for purchase in customer:       # For price in inner list:
            customer_total += purchase  # Add the price to value of purchases for inner list
        if customer_total >= 100:       # After looping over all prices in inner list, if
                                        # total >= 100
            count+=1                    # Increment the counter
    return count

In [ ]:
LA_counties = []

for state, county in state_county_tuples:
  if state == 'Louisiana':
    LA_counties.append(county)
LA_counties

['East Baton Rogue']

In [ ]:
aqi_dict = {}
for state, county, aqi in epa_tuples:
    if state in aqi_dict:
        aqi_dict[state].append((county, aqi))
    else:
        aqi_dict[state] = [(county, aqi)]

aqi_dict['California']

================end=================================

# **Lists**

append() adds items at the end of the list

In [ ]:
fruits = ['apple','banana','kiwi']

In [ ]:
fruits.append('strawberry')
print(fruits)

['apple', 'banana', 'kiwi', 'strawberry']


insert() adds item with index

In [ ]:
fruits.insert('pineapple')

TypeError: insert expected 2 arguments, got 1

In [ ]:
fruits.insert(2, 'orange')
print(fruits)

['apple', 'banana', 'orange', 'kiwi', 'strawberry']


In [ ]:
fruits.insert(0, 'pineapple')
print(fruits)

['pineapple', 'apple', 'banana', 'orange', 'kiwi', 'strawberry']


In [ ]:
fruits.remove('pineapple')
print(fruits)

['apple', 'banana', 'orange', 'kiwi', 'strawberry']


pop() removes last item

In [ ]:
fruits.pop()
print(fruits)

['apple', 'banana', 'orange', 'kiwi']


or by using indexing we can remove specific item

In [ ]:
fruits.pop(2)
print(fruits)

['apple', 'banana', 'kiwi']


In [ ]:
fruits.index('banana')

1

In [ ]:
fruits.index('kiwi')

2

there's no replace function. but you can replace it by simply assiging new item to the list by indexing

In [ ]:
fruits[2]='mango'
print(fruits)

['apple', 'banana', 'mango']


In [ ]:
fruits.replace('mango','elephant')

AttributeError: 'list' object has no attribute 'replace'

In [ ]:
fruits[2] = 'elephant'
print(fruits)

['apple', 'banana', 'elephant']


In [ ]:
# change list to tuple

fruits = tuple(fruits)
print(fruits)

('apple', 'banana', 'elephant')


In [ ]:
fruits.append('bicycle')
print(fruits)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
fruits[2] = 'bicycle'
print(fruits)

TypeError: 'tuple' object does not support item assignment

In [ ]:
fruits

('apple', 'banana', 'elephant')

# **zip()**

In [ ]:
f_names = ['ganesh','emma','susma']
l_names = ['gurung','hayun','grg']

full_names = zip(f_names, l_names)

print(full_names)

In [ ]:
print(list(full_names))

[('ganesh', 'gurung'), ('emma', 'hayun'), ('susma', 'grg')]


In [ ]:
full_names = [('ganesh', 'gurung'), ('emma', 'hayun'), ('susma', 'grg')]

zip(*full_names)

In [ ]:
print(f_names)
print()
print(l_names)

['ganesh', 'emma', 'susma']

['gurung', 'hayun', 'grg']


# **enumerate()**

In [ ]:
full_names = [('ganesh', 'gurung'), ('emma', 'hayun'), ('susma', 'grg')]

In [ ]:
for index, names in enumerate(full_names):
  print(index, names)

0 ('ganesh', 'gurung')
1 ('emma', 'hayun')
2 ('susma', 'grg')


In [ ]:
for index, names in enumerate(full_names, 1):
  print(index, names)

1 ('ganesh', 'gurung')
2 ('emma', 'hayun')
3 ('susma', 'grg')


In [ ]:
numbers = [1,2,4,5]
new_list =  [x + 10 for x in numbers]
print(new_list)

[11, 12, 14, 15]


# **=============================**

In [ ]:
# 1. ### YOUR CODE HERE ###
state_names = ['Arizona','California','California','Kentucky','Louisiana']

# 2. ### YOUR CODE HERE ###
county_names = ['Maricopa','Alameda','Sacramento','Jefferson','East Baton Rogue']

In [ ]:
state_county_tuples = []
for i in range(len(state_names)):
    state_county_tuples.append((state_names[i], county_names[i]))

state_county_tuples

[('Arizona', 'Maricopa'),
 ('California', 'Alameda'),
 ('California', 'Sacramento'),
 ('Kentucky', 'Jefferson'),
 ('Louisiana', 'East Baton Rogue')]

# **============================**

In [ ]:
# 1. ### YOUR CODE HERE ###
state_county_zipped = list(zip(state_names, county_names))

# 2. ### YOUR CODE HERE ###
state_county_zipped == state_county_tuples

True

In [ ]:
ca_counties = []
for state, county in state_county_tuples:
    if state=='California':
        ca_counties.append(county)
ca_counties

['Alameda', 'Sacramento']

In [ ]:
state_county_lists = [list(i) for i in state_county_tuples]
state_county_lists

[['Arizona', 'Maricopa'],
 ['California', 'Alameda'],
 ['California', 'Sacramento'],
 ['Kentucky', 'Jefferson'],
 ['Louisiana', 'East Baton Rogue']]

In [ ]:
ca_counties = [county for (state, county) in state_county_tuples if state =='California']
ca_counties

['Alameda', 'Sacramento']

# **============================**

In [ ]:
LA_counties = []

for state, county in state_county_tuples:
  if state == 'Louisiana':
    LA_counties.append(county)
LA_counties

['East Baton Rogue']

In [ ]:
la_counties = []
for state, county in state_county_tuples:
    if state=='Louisiana':
        la_counties.append(county)
la_counties

['East Baton Rogue']

# **Dictionary**

In [ ]:
new_dict_1 = {}

new_dict_2 = dict()     # this is function

In [ ]:
invalid_dict = {'number': 1,2,3}
print(invalid_dict)

In [ ]:
valid_dict = {'numbers': [1,2,3]}
print(valid_dict)

{'numbers': [1, 2, 3]}


In [ ]:
# access values
my_dict = {'numbers':[1,2,3],
           'words':['a','b','c']}

print(my_dict['numbers'])
print()
print(my_dict['words'])

[1, 2, 3]

['a', 'b', 'c']


In [ ]:
# use values() method:
print(my_dict.values())

dict_values([[1, 2, 3], ['a', 'b', 'c']])


In [ ]:
# add a new key
my_dict['floats']= [1.0,2.0,3.0]
print(my_dict)

{'numbers': [1, 2, 3], 'words': ['a', 'b', 'c'], 'floats': [1.0, 2.0, 3.0]}


In [ ]:
print('numbers' in my_dict)
print('words' in my_dict)
print('int' in my_dict)

True
True
False


In [ ]:
# delete key-value pair
del my_dict['floats']
print(my_dict)

{'numbers': [1, 2, 3], 'words': ['a', 'b', 'c']}


In [ ]:
print(my_dict.keys())

dict_keys(['numbers', 'words'])


In [ ]:
print(my_dict.values())

dict_values([[1, 2, 3], ['a', 'b', 'c']])


# **set()**

In [ ]:
lst1 =[1.5, ('a', 'b', 'c'), 1.5]
set(lst1)

{('a', 'b', 'c'), 1.5}

In [ ]:
lst1 =[1.5, {'a', 'b', 'c'}, 1.5]
set(lst1)

In [ ]:
# union() method

set_1 = {'a', 'b', 'c'}
set_2 = {'b', 'c', 'd'}

print(set_1.union(set_2))
print(set_1 | set_2)

{'a', 'c', 'b', 'd'}
{'a', 'c', 'b', 'd'}


In [ ]:
# intersection() method

set_1 = {'a', 'b', 'c'}
set_2 = {'b', 'c', 'd'}

print(set_1.intersection(set_2))
print(set_1 & set_2)


{'b', 'c'}
{'b', 'c'}


In [ ]:
# difference
set_1 = {'a', 'b', 'c'}
set_2 = {'b', 'c', 'd'}

print(set_1.difference(set_2))
print(set_1 - set_2)

# prints a new set with element that are not in other sets

{'a'}
{'a'}


In [ ]:
# symmetric_difference

set_1 = {'a', 'b', 'c'}
set_2 = {'b', 'c', 'd'}

print(set_1.symmetric_difference(set_2))
print(set_1 ^ set_2)

{'a', 'd'}
{'a', 'd'}


# **====================================**

Convert state_list, county_list, and aqi_list to a list of tuples, where each tuple contains information for a single record: (state, county, aqi).

Assign the result to a variable called epa_tuples.

In [ ]:
import ada_c2_labs as lab
state_list = lab.fetch_epa('state')
county_list = lab.fetch_epa('county')
aqi_list = lab.fetch_epa('aqi')

In [ ]:
epa_tuples = list(zip(state_list, county_list, aqi_list))

* Create a dictionary called aqi_dict:
* Use a loop to unpack information from each tuple in epa_tuples.
* Your dictionary's keys should be states.
* The value at each key should be a list of tuples, where each tuple is a
  county-AQI pair of a record from a given state.

In [ ]:
aqi_dict = {}
for state, county, aqi in epa_tuples:
    if state in aqi_dict:
        aqi_dict[state].append((county, aqi))
    else:
        aqi_dict[state] = [(county, aqi)]

In [ ]:
aqi_dict['Vermont']

Use your Python skills to calculate the number of readings that were recorded in the state of Arizona.

In [ ]:
len(aqi_dict['Arizona'])

Use your Python skills to calculate the mean of the AQI readings that were recorded in the state of California. Note that there are many different approaches you can take. Be creative!

In [ ]:
ca_aqi_list = [aqi for county, aqi in aqi_dict['California']]


ca_aqi_mean = sum(ca_aqi_list) / len(ca_aqi_list)
ca_aqi_mean

* Define a function called county_counter that takes one argument:

* state - a string of the name of a U.S. state
* Return county_dict - a dictionary object whose keys are counties of the state given in the function's argument. For each county key, the corresponding value should be the count of the number of times that county is represented in the AQI data for that state.

In [ ]:
def county_counter(state):
    county_dict = {}
    for county, aqi in aqi_dict[state]:
        if county in county_dict:
            county_dict[county] +=1
        else:
            county_dict[county] = 1
    return county_dict

Use the county_counter() function to calculate how many AQI readings were from Washington County, Pennsylvania.

In [ ]:
pa_dict = county_counter('Pennsylvania')
pa_dict['Washington']

# **=============================================**

# **Numpy and Pandas**

* NumPy is used for high-performance vector and matrix computations.
* Pandas is a library for manipulating and analyzing tabular data.
* Seaborn and matplotlib are both libraries used to create graphs, charts, and other data visualizations.

In [ ]:
list_a = [1,2,3]
list_b = [2,4,6]

In [ ]:
print(list_a * list_b)

TypeError: can't multiply sequence by non-int of type 'list'

using a loop

In [ ]:
# create a empty list_c

list_c = []

for i in range (len(list_a)):
  list_c.append(list_a[i] * list_b[i])
list_c

[2, 8, 18]

use numpy as vectorized computation

In [ ]:
import numpy as np

array_a = np.array(list_a)
array_b = np.array(list_b)

print(array_a * array_b)

[ 2  8 18]


In [ ]:
import numpy as gg

array_c = gg.array(list_a)
array_d = gg.array(list_b)

print(array_c * array_d)

[ 2  8 18]


# **datetime**

In [ ]:
import datetime
date = datetime.date(1977, 5, 8)       # assign a date to a variable
print(date)                            # print date
print(date.year)                       # print the year that the date is in

delta = datetime.timedelta(days=30)    # assign a timedelta of 30 days to a
                                       # variable
print(date - delta)                    # print date of 30 days prior

1977-05-08
1977
1977-04-08


# **math**

In [ ]:
import math
print(math.exp(0))          # e**0
print(math.log(1))          # ln(1)
print(math.factorial(4))    # 4!
print(math.sqrt(100))       # square root of 100

1.0
0.0
24
10.0


In [ ]:
# using a loop

def factorial(n):
  result = 1
  for i in range (1, n+1):
    result *= i
  return result

In [ ]:
result = factorial(4)

In [ ]:
print(result)

24


In [ ]:
# using method

print(math.factorial(4))

24


In [ ]:
def factorial(n):
    result = 1                 # Initialize the result variable to 1
    for i in range(1, n + 1):  # Loop through numbers from 1 to n (inclusive)     .it creates a range, which is from (1,5). starts from 1 and ends to 5 which is 1,2,3,4.
        result *= i            # Multiply the current value of result by the current value of i
    return result              # Return the final result after the loop

result = factorial(4)          # Call the factorial function with argument 4
print(result)                  # Print the result


24


Explanation:

result = 1: Before starting the loop, we initialize a variable result to 1. This variable will store the factorial of the input number n.

for i in range(1, n + 1): This line sets up a loop that iterates over the numbers from 1 to n (inclusive). In this case, n is 4, so the loop will iterate over the numbers 1, 2, 3, and 4.

result *= i: Inside the loop, we multiply the current value of result by the current value of i. This accumulates the product of all numbers from 1 to n into the result variable. In each iteration, i takes on the values 1, 2, 3, and 4, so we are effectively multiplying result by each of these numbers.

After the loop finishes, we have multiplied all the numbers from 1 to n together, resulting in the factorial of n, which is stored in the result variable.

return result: Finally, we return the computed factorial value stored in the result variable.

So, for factorial(4), the loop calculates 1 * 1 * 2 * 3 * 4, which equals 24, and this value is returned.







# **random**

In [ ]:
import random
print(random.random())                   # gives result from 0.0 <= X < 1.0
print(random.choice([1,2,3,4,5,6]))      # choose a random element from a sequence
print(random.randint(1,6))
print(random.choice([0,'X']))

0.8717606715061363
4
4
X


# **Arrays**
np.array()

In [ ]:
import numpy as np

array_1d = np.array([1,2,3])
print(array_1d)

print('1d array is similar to a list')

[1 2 3]
1d array is similar to a list


In [ ]:
array_2d = np.array([(1,2,3),(4,5,6)])
print(array_2d)

print('2d array is similar to a table')

[[1 2 3]
 [4 5 6]]
2d array is similar to a table


In [ ]:
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
print(array_3d)

print('3d array is similar to two tables')

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]
3d array is similar to two tables


np.zeros()

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

np.ones()

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

np.full()

In [ ]:
np.full((5,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [ ]:
# ndarray.flatten()

array_2d = np.array([(1,2,3),(4,5,6)])
print(array_2d)


[[1 2 3]
 [4 5 6]]


In [ ]:
array_2d.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# ndarray.reshape

array_2d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_2d.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# ndarray.tolist()

array_2d.tolist()

[[1, 2, 3], [4, 5, 6]]

In [ ]:
print(array_2d.max())
print(array_2d.min())
print(array_2d.mean())
print(array_2d.std())

6
1
3.5
1.707825127659933


In [ ]:
print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size)

(2, 3)
int64
6


# **Method is a function that belongs to a class.**

In [ ]:
# iloc function gives result starting, ending and step. it gives results upto but not included.
# iloc[0:3] gives result starting from 0 upto 3 which is 0,1,2.

In [ ]:
import pandas as pd
d = {'col1': [1,2], 'col2':[3,4]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     3
1     2     4

In [ ]:
import numpy as np
df2 = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]),
                   columns=['a','b','c'])
df2

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df = pd.DataFrame({
   'A': ['alpha', 'apple', 'arsenic', 'angel', 'android'],
   'B': [1, 2, 3, 4, 5],
   'C': ['coconut', 'curse', 'cassava', 'cuckoo', 'clarinet'],
   'D': [6, 7, 8, 9, 10]
   },
   index=['row_0', 'row_1', 'row_2', 'row_3', 'row_4'])
df

A  B         C   D
row_0    alpha  1   coconut   6
row_1    apple  2     curse   7
row_2  arsenic  3   cassava   8
row_3    angel  4    cuckoo   9
row_4  android  5  clarinet  10

In [ ]:
print(df.loc['row_1'])

A    apple
B        2
C    curse
D        7
Name: row_1, dtype: object


In [ ]:
print(df.loc[['row_1']])

           A  B      C  D
row_1  apple  2  curse  7


In [ ]:
print(df.loc[['row_2','row_4']])

             A  B         C   D
row_2  arsenic  3   cassava   8
row_4  android  5  clarinet  10


In [ ]:
print(df.loc[['row_2','row_4']])

             A  B         C   D
row_2  arsenic  3   cassava   8
row_4  android  5  clarinet  10


# **Boolean masking**
A filtering technique that overlays a Boolean grid onto a dataframe in order to select only the values in the dataframe that align with the True values of the grid.

#   Operator Logic


*  ampersand  =  &  ,   and     
*  verical bar =  |   ,  or     
*   tilda =  ~  ,   not     


In [ ]:
data = {'planet': ['Mercury', 'Venus', 'Earth', 'Mars',
                   'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
       'radius_km': [2440, 6052, 6371, 3390, 69911, 58232,
                     25362, 24622],
       'moons': [0, 0, 1, 2, 80, 83, 27, 14]
        }
df = pd.DataFrame(data)
df

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83
6   Uranus      25362     27
7  Neptune      24622     14

In [ ]:
print(df['moons']<20)

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: moons, dtype: bool


In [ ]:
print(df[df['moons']<20])

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24622     14


In [ ]:
mask = df['moons']<20
df[mask]

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24622     14

In [ ]:
mask = (df['moons']<10) | (df['moons']>50)
print(mask)

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7    False
Name: moons, dtype: bool


In [ ]:
mask = (df['moons']<10) | (df['moons']>50)
df[mask]                                       # it will give dataframe of true conditions only

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83

In [ ]:
mask = (df['moons']>20) & ~(df['moons'] == 80) & ~(df['radius_km']<5000)
df[mask]

planet  radius_km  moons
5  Saturn      58232     83
6  Uranus      25362     27

In [ ]:
mask = (df['moons']>20) & (df['moons'] != 80) & (df['radius_km']>5000)         # same statement different syntax just to understand
df[mask]

planet  radius_km  moons
5  Saturn      58232     83
6  Uranus      25362     27

# **groupby()**
A pandas DataFrame method that groups rows of the dataframe together based on their values at one or more columns, which further analysis of the groups.

In [ ]:
import pandas as pd


In [ ]:
clothes = pd.DataFrame({'type': ['pants', 'shirt', 'shirt', 'pants', 'shirt', 'pants'],
                       'color': ['red', 'blue', 'green', 'blue', 'green', 'red'],
                       'price_usd': [20, 35, 50, 40, 100, 75],
                       'mass_g': [125, 440, 680, 200, 395, 485]})


clothes

type  color  price_usd  mass_g
0  pants    red         20     125
1  shirt   blue         35     440
2  shirt  green         50     680
3  pants   blue         40     200
4  shirt  green        100     395
5  pants    red         75     485

In [ ]:
grouped = clothes.groupby('type')
print(grouped)

In [ ]:
clothes.iloc[1:3]

type  color  price_usd  mass_g
1  shirt   blue         35     440
2  shirt  green         50     680

In [ ]:
mask = (clothes['mass_g'] > 440)
clothes[mask]

type  color  price_usd  mass_g
2  shirt  green         50     680
5  pants    red         75     485

In [ ]:
mask = clothes['color'] == 'blue'
clothes[mask]

type color  price_usd  mass_g
1  shirt  blue         35     440
3  pants  blue         40     200

In [ ]:
# masking step 1
mask = clothes['type'] == 'shirt'
clothes[mask]

type  color  price_usd  mass_g
1  shirt   blue         35     440
2  shirt  green         50     680
4  shirt  green        100     395

In [ ]:
# masking step 2
shirt_df = clothes[mask]
shirt_df

type  color  price_usd  mass_g
1  shirt   blue         35     440
2  shirt  green         50     680
4  shirt  green        100     395

In [ ]:
# together looks like this
mask = clothes['type'] == 'shirt'
df_shirt = clothes[mask]
df_shirt

type  color  price_usd  mass_g
1  shirt   blue         35     440
2  shirt  green         50     680
4  shirt  green        100     395

# **concat()**
a pandas function that combines data either by adding it horizontally as new columns for existing rows or vertically as new rows for existing columns
* axis 1 = rows
* axis 0 = columns

* df3 = pd.concat([df1,df2], axis = 0) # for rows
* df3 = pd.concat([df1,df2], axis = 1) # for columns

to clear or reset original df
* df3 = df3.reset_index(drop = true)
* df3

# **merge()**
a pandas function that joins two dataframes together; it only combines data by extending along axis one (1) horizontally

* inner = pd.merge(df3, df4, on='planet', how = 'inner')
* inner

* outer = pd.merge(df3, df4, on='planet', how = 'outer')
* outer

* left = pd.merge(df3, df4, on='planet', how = 'left')
* left

* right = pd.merge(df3, df4, on='planet', how = 'right')
* right

Case Study : Dataframes with pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/annual_aqi_by_county_2023.csv')
df.head()

State   County  Year  Days with AQI  Good Days  Moderate Days  \
0  Alabama  Baldwin  2023            170        143             27   
1  Alabama     Clay  2023            155        109             46   
2  Alabama   DeKalb  2023            212        155             55   
3  Alabama   Elmore  2023            118        102             16   
4  Alabama   Etowah  2023            181        126             55   

   Unhealthy for Sensitive Groups Days  Unhealthy Days  Very Unhealthy Days  \
0                                    0               0                    0   
1                                    0               0                    0   
2                                    2               0                    0   
3                                    0               0                    0   
4                                    0               0                    0   

   Hazardous Days  Max AQI  90th Percentile AQI  Median AQI  Days CO  \
0               0       90                   54          40        0   
1               0       83                   61          40        0   
2               0      133                   63          43        0   
3               0       90                   54          40        0   
4               0      100                   64          43        0   

   Days NO2  Days Ozone  Days PM2.5  Days PM10  
0         0          84          86          0  
1         0           0         155          0  
2         0         141          71          0  
3         0         118           0          0  
4         0          74         107          0

In [ ]:
top_3 = df.iloc[:, :5]
top_3

State      County  Year  Days with AQI  Good Days
0    Alabama     Baldwin  2023            170        143
1    Alabama        Clay  2023            155        109
2    Alabama      DeKalb  2023            212        155
3    Alabama      Elmore  2023            118        102
4    Alabama      Etowah  2023            181        126
..       ...         ...   ...            ...        ...
944  Wyoming    Sublette  2023            211         92
945  Wyoming  Sweetwater  2023            212        125
946  Wyoming       Teton  2023            244        203
947  Wyoming       Uinta  2023            181        181
948  Wyoming      Weston  2023            181        154

[949 rows x 5 columns]

In [ ]:
# metadata
top_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   State          949 non-null    object
 1   County         949 non-null    object
 2   Year           949 non-null    int64 
 3   Days with AQI  949 non-null    int64 
 4   Good Days      949 non-null    int64 
dtypes: int64(3), object(2)
memory usage: 37.2+ KB


In [ ]:
# summary statistics
top_3.describe()

Year  Days with AQI   Good Days
count   949.0     949.000000  949.000000
mean   2023.0     194.891465  146.892518
std       0.0      51.563261   44.509908
min    2023.0      29.000000   25.000000
25%    2023.0     179.000000  119.000000
50%    2023.0     182.000000  150.000000
75%    2023.0     241.000000  173.000000
max    2023.0     274.000000  271.000000

In [ ]:
# rows per state
top_3['State'].value_counts()

California              50
Texas                   44
Florida                 38
Ohio                    37
Pennsylvania            36
North Carolina          34
Indiana                 33
Virginia                30
Wisconsin               29
Washington              29
Georgia                 28
New York                27
Michigan                26
Kentucky                25
Colorado                24
Illinois                23
Tennessee               23
Louisiana               22
Oregon                  21
Oklahoma                20
Minnesota               20
Missouri                19
Montana                 18
Wyoming                 18
Idaho                   18
Maryland                16
Iowa                    16
New Jersey              15
Alabama                 14
Utah                    14
South Carolina          14
Massachusetts           13
Arizona                 13
West Virginia           13
Arkansas                11
New Mexico              11
Maine                   11
S

In [ ]:
# sort by Days with AQI
top_3_sorted = top_3.sort_values(by='Days with AQI', ascending = False)   # ascending true goes from lower to higher, false goes vice versa
top_3_sorted.head(10)

State            County  Year  Days with AQI  Good Days
283       Iowa             Scott  2023            274        147
331  Louisiana           Orleans  2023            274        237
217   Illinois              Cook  2023            274        116
24     Arizona          Maricopa  2023            274         66
325  Louisiana  East Baton Rouge  2023            274        177
346      Maine           Hancock  2023            274        235
820       Utah         Salt Lake  2023            274        124
477   Nebraska           Douglas  2023            274        161
831   Virginia         Arlington  2023            274        246
837   Virginia           Fairfax  2023            274        225

In [ ]:
top_3_sorted.tail(10)

State         County  Year  Days with AQI  Good Days
151        Florida       Okaloosa  2023             57         48
341      Louisiana     Terrebonne  2023             55         53
894  West Virginia       Harrison  2023             53         43
714    Puerto Rico        Fajardo  2023             52         48
605           Ohio     Columbiana  2023             41         40
399       Michigan         Monroe  2023             40         37
844       Virginia  Hopewell City  2023             32         32
465        Montana           Hill  2023             30         25
715    Puerto Rico        Guayama  2023             29         28
834       Virginia        Carroll  2023             29         29

In [ ]:
top_3_sorted.iloc[10:12]

State        County  Year  Days with AQI  Good Days
841        Virginia  Hampton City  2023            274        230
575  North Carolina   Mecklenburg  2023            274        173

In [ ]:
# california data
# basic boolean masking

mask = top_3_sorted['State']=='California'
ca_df = top_3_sorted[mask]                            # assign variable ca_df to the mask and print first 10 rows
ca_df.head(10)

State          County  Year  Days with AQI  Good Days
55  California            Inyo  2023            273        117
73  California       San Diego  2023            271        166
47  California          Colusa  2023            269        152
89  California          Tulare  2023            243        115
61  California        Mariposa  2023            243        179
69  California       Riverside  2023            243         67
72  California  San Bernardino  2023            243         76
51  California          Fresno  2023            243        118
71  California      San Benito  2023            242        209
81  California          Shasta  2023            242        203

In [ ]:
# validate CA data
ca_df.shape
# attributes does not use parentheses

(50, 5)

In [ ]:
# rows per county
ca_df['County'].value_counts()

Inyo               1
Calaveras          1
Yolo               1
Imperial           1
Orange             1
Santa Barbara      1
El Dorado          1
Butte              1
Mono               1
Nevada             1
Plumas             1
San Luis Obispo    1
Stanislaus         1
San Diego          1
Del Norte          1
Tuolumne           1
Amador             1
Glenn              1
Sutter             1
Tehama             1
San Joaquin        1
Trinity            1
Lake               1
Siskiyou           1
Ventura            1
Los Angeles        1
Santa Cruz         1
Kings              1
Colusa             1
Tulare             1
Mariposa           1
Riverside          1
San Bernardino     1
Fresno             1
San Benito         1
Shasta             1
Sacramento         1
Kern               1
Humboldt           1
Solano             1
Alameda            1
Contra Costa       1
Sonoma             1
Monterey           1
San Francisco      1
San Mateo          1
Marin              1
Santa Clara  

In [ ]:
ca_df['County'].sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of 55               Inyo
73          San Diego
47             Colusa
89             Tulare
61           Mariposa
69          Riverside
72     San Bernardino
51             Fresno
71         San Benito
81             Shasta
70         Sacramento
56               Kern
53           Humboldt
83             Solano
43            Alameda
48       Contra Costa
84             Sonoma
64           Monterey
74      San Francisco
77          San Mateo
60              Marin
79        Santa Clara
67             Placer
57              Kings
80         Santa Cruz
59        Los Angeles
91            Ventura
92               Yolo
54           Imperial
66             Orange
78      Santa Barbara
50          El Dorado
45              Butte
63               Mono
65             Nevada
68             Plumas
76    San Luis Obispo
46          Calaveras
85         Stanislaus
49          Del Norte
90           Tuolumne
44             Amador
52            

In [ ]:
# calculate mean AQI for los angeles county
mask = ca_df['County']=='San Francisco'
ca_df[mask]['Days with AQI'].mean()

213.0

In [ ]:
# groupby()
# mean for all states
top_3.groupby('State').mean()[['Days with AQI']]

<ipython-input-68-f7247a5a4612>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  top_3.groupby('State').mean()[['Days with AQI']]


Days with AQI
State                              
Alabama                  168.857143
Alaska                   188.000000
Arizona                  271.692308
Arkansas                 177.272727
California               196.920000
Colorado                 214.041667
Connecticut              169.375000
Country Of Mexico        273.000000
District Of Columbia     244.000000
Florida                  177.868421
Georgia                  205.642857
Hawaii                   190.333333
Idaho                    182.777778
Illinois                 257.826087
Indiana                  235.606061
Iowa                     213.562500
Kansas                   177.500000
Kentucky                 167.240000
Louisiana                241.545455
Maine                    250.909091
Maryland                 211.125000
Massachusetts            180.384615
Michigan                 158.346154
Minnesota                173.100000
Mississippi              171.200000
Missouri                 122.052632
Montana                  177.500000
Nebraska                 241.333333
Nevada                   190.888889
New Hampshire            172.428571
New Jersey               175.266667
New Mexico               186.272727
New York                 253.925926
North Carolina           215.970588
North Dakota             212.555556
Ohio                     211.216216
Oklahoma                 195.550000
Oregon                   197.857143
Pennsylvania             182.750000
Puerto Rico               93.250000
Rhode Island             184.666667
South Carolina           234.500000
South Dakota             180.500000
Tennessee                184.434783
Texas                    182.750000
Utah                     253.285714
Vermont                  181.000000
Virginia                 176.800000
Washington               180.000000
West Virginia            142.923077
Wisconsin                149.068966
Wyoming                  191.166667

In [ ]:
# these codes are uninteractable for contatenate examples
# Add the data from other_states as new rows beneath the data from top3.
# Assign the result to a new dataframe called combined_df.

Verify that the length of combined_df is equal to the sum of the lengths of top3 and other_states.
combined_df = pd.concat([top3, other_states], axis = 0)

len(combined_df) == len(top3) + len(other_states)


In [ ]:
mask = (combined_df['state_name']=='Washington') & (combined_df['aqi'] >= 51)
combined_df[mask]